name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint src test
          check-name: clj-kondo
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: lein deps
      - name: Run tests
        run: lein ci
      - name: upload-code-coverage-report
        uses: codecov/codecov-action@v1
        with:
          file: target/coverage/codecov.json
